export const SET_ORDER = 'SET_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const RESET_ORDER = 'RESET_ORDER';

export const ADD_ORDER_DETAIL = 'ADD_ORDER_DETAIL';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';
export const UPDATE_ORDER_DETAIL = 'UPDATE_ORDER_DETAIL';
export const DELETE_ORDER_DETAIL = 'DELETE_ORDER_DETAIL';
export const RESET_ORDER_DETAILS = 'RESET_ORDER_DETAILS';

export const SET_DESIGNER = 'SET_DESIGNER';
export const UPDATE_DESIGNER = 'UPDATE_DESIGNER';
export const RESET_DESIGNER = 'RESET_DESIGNER';

export const ADD_DESIGNER_CLOTHING = 'ADD_DESIGNER_CLOTHING';
export const SET_DESIGNER_CLOTHING = 'SET_DESIGNER_CLOTHING';
export const UPDATE_DESIGNER_CLOTHING = 'UPDATE_DESIGNER_CLOTHING';
export const DELETE_DESIGNER_CLOTHING = 'DELETE_DESIGNER_CLOTHING';
export const RESET_DESIGNER_CLOTHES = 'RESET_DESIGNER_CLOTHES';

export const SET_EMPLOYEE = 'SET_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const RESET_EMPLOYEE = 'RESET_EMPLOYEE';

export const UPDATE_REPORT_FILTER = 'UPDATE_REPORT_FILTER';
export const SHOW_REPORT_RESULTS = 'SHOW_REPORT_RESULTS';
export const SET_REPORT_ERRORS = 'SET_REPORT_ERRORS';
export const RESET_REPORT = 'RESET_REPORT';

export const SET_NAVBAR_TITLE = 'SET_NAVBAR_TITLE';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
